// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StonkWatch.Web.Data;

#nullable disable

namespace StonkWatch.Web.Data.Migrations
{
    [DbContext(typeof(StonkWatchDbContext))]
    [Migration("20260818184521_AddLiveWatchlist")]
    partial class AddLiveWatchlist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StonkWatch.Web.Data.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("alert_type");

                    b.Property<bool>("AutoGenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_generated");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<string>("ConditionSignal")
                        .HasColumnType("text")
                        .HasColumnName("condition_signal");

                    b.Property<DateTimeOffset?>("LastChecked")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked");

                    b.Property<DateTimeOffset?>("LastNotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_notified_at");

                    b.Property<decimal?>("LevelHigh")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("level_high");

                    b.Property<string>("LevelKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("level_key");

                    b.Property<decimal?>("LevelLow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("level_low");

                    b.Property<decimal?>("TriggerPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("trigger_price");

                    b.Property<bool>("Triggered")
                        .HasColumnType("boolean")
                        .HasColumnName("triggered");

                    b.Property<DateTimeOffset?>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("ix_alerts_candidate_id");

                    b.HasIndex("CandidateId", "LevelKey")
                        .IsUnique()
                        .HasDatabaseName("ix_alerts_candidate_id_level_key")
                        .HasFilter("level_key IS NOT NULL");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("StonkWatch.Web.Data.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<string>("Conviction")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("conviction");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<decimal?>("CurrentPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("current_price");

                    b.Property<string>("DataQuality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("data_quality");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<string>("Exchange")
                        .HasColumnType("text")
                        .HasColumnName("exchange");

                    b.Property<decimal?>("Invalidation")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("invalidation");

                    b.Property<decimal?>("LastQuote")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("last_quote");

                    b.Property<DateTimeOffset?>("LastReviewed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reviewed");

                    b.Property<string>("MainRisk")
                        .HasColumnType("text")
                        .HasColumnName("main_risk");

                    b.Property<string>("NextEvent")
                        .HasColumnType("text")
                        .HasColumnName("next_event");

                    b.Property<string>("PreferredSetup")
                        .HasColumnType("text")
                        .HasColumnName("preferred_setup");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset?>("QuoteAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quote_at");

                    b.Property<decimal?>("ReclaimTrigger1")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("reclaim_trigger1");

                    b.Property<decimal?>("ReclaimTrigger2")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("reclaim_trigger2");

                    b.Property<decimal?>("ReviewedPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("reviewed_price");

                    b.Property<decimal?>("SecondarySupportHigh")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("secondary_support_high");

                    b.Property<decimal?>("SecondarySupportLow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("secondary_support_low");

                    b.Property<string>("SourceNotes")
                        .HasColumnType("text")
                        .HasColumnName("source_notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal?>("SupportHigh")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("support_high");

                    b.Property<decimal?>("SupportLow")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("support_low");

                    b.Property<decimal?>("T1")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("t1");

                    b.Property<decimal?>("T2")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("t2");

                    b.Property<string>("Thesis")
                        .HasColumnType("text")
                        .HasColumnName("thesis");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticker");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_candidates");

                    b.HasIndex("Ticker")
                        .IsUnique()
                        .HasDatabaseName("ix_candidates_ticker");

                    b.ToTable("candidates", (string)null);
                });

            modelBuilder.Entity("StonkWatch.Web.Data.Entities.JobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AlertsFired")
                        .HasColumnType("integer")
                        .HasColumnName("alerts_fired");

                    b.Property<int>("CandidatesChecked")
                        .HasColumnType("integer")
                        .HasColumnName("candidates_checked");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("job");

                    b.Property<int>("NotificationsSent")
                        .HasColumnType("integer")
                        .HasColumnName("notifications_sent");

                    b.Property<string>("SkipReason")
                        .HasColumnType("text")
                        .HasColumnName("skip_reason");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_job_runs");

                    b.HasIndex("Job", "StartedAt")
                        .HasDatabaseName("ix_job_runs_job_started_at");

                    b.ToTable("job_runs", (string)null);
                });

            modelBuilder.Entity("StonkWatch.Web.Data.Entities.ReviewLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<bool>("LevelsChanged")
                        .HasColumnType("boolean")
                        .HasColumnName("levels_changed");

                    b.Property<string>("NextAction")
                        .HasColumnType("text")
                        .HasColumnName("next_action");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price");

                    b.Property<DateTimeOffset>("ReviewDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("review_date");

                    b.Property<string>("StatusAtReview")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_at_review");

                    b.Property<string>("ThesisImpact")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("thesis_impact");

                    b.Property<string>("WhatChanged")
                        .HasColumnType("text")
                        .HasColumnName("what_changed");

                    b.HasKey("Id")
                        .HasName("pk_review_log");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("ix_review_log_candidate_id");

                    b.ToTable("review_log", (string)null);
                });

            modelBuilder.Entity("StonkWatch.Web.Data.Entities.WatchlistGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_watchlist_groups");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_watchlist_groups_name");

                    b.ToTable("watchlist_groups", (string)null);
                });

            modelBuilder.Entity("StonkWatch.Web.Data.Entities.WatchlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("display_name");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_watchlist_items");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("ix_watchlist_items_symbol");

                    b.HasIndex("GroupId", "SortOrder")
                        .HasDatabaseName("ix_watchlist_items_group_id_sort_order");

                    b.ToTable("watchlist_items", (string)null);
                });

            modelBuilder.Entity("StonkWatch.Web.Data.Entities.Alert", b =>
                {
                    b.HasOne("StonkWatch.Web.Data.Entities.Candidate", "Candidate")
                        .WithMany("Alerts")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_candidates_candidate_id");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("StonkWatch.Web.Data.Entities.ReviewLogEntry", b =>
                {
                    b.HasOne("StonkWatch.Web.Data.Entities.Candidate", "Candidate")
                        .WithMany("ReviewLogs")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_log_candidates_candidate_id");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("StonkWatch.Web.Data.Entities.WatchlistItem", b =>
                {
                    b.HasOne("StonkWatch.Web.Data.Entities.WatchlistGroup", "Group")
                        .WithMany("Items")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_watchlist_items_watchlist_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("StonkWatch.Web.Data.Entities.Candidate", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("ReviewLogs");
                });

            modelBuilder.Entity("StonkWatch.Web.Data.Entities.WatchlistGroup", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
