using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using Microsoft.Extensions.Time.Testing;
using StonkWatch.Web.Data;
using StonkWatch.Web.Data.Entities;
using StonkWatch.Web.Services.Monitoring;

namespace StonkWatch.Web.Tests;

[Collection(PostgresCollection.Name)]
public class PriceCheckJobTests(PostgresFixture fixture) : IAsyncLifetime
{
    // A Friday inside the regular session, so the market calendar lets ticks through.
    private static readonly DateTimeOffset MarketOpen = new(2026, 7, 31, 15, 0, 0, TimeSpan.Zero);

    private readonly FakeTimeProvider _time = new(MarketOpen);
    private readonly FakeQuoteProvider _quotes = new();
    private readonly RecordingNotifier _notifier = new();

    // Most tests here are about crossing and suppression behaviour, not the session window,
    // so they advance the clock freely and bypass the calendar. The two market-hours tests
    // below turn the gate back on; MarketCalendarTests covers the window itself.
    private readonly MonitoringOptions _options = new()
    {
        Enabled = true,
        IgnoreMarketHours = true,
        ReArmPercent = 0.5m,
        MinNotifyHours = 6
    };

    public Task InitializeAsync() => fixture.ResetAsync();

    public Task DisposeAsync() => Task.CompletedTask;

    private async Task<JobRun> RunAsync()
    {
        await using var db = fixture.CreateContext();
        var job = new PriceCheckJob(
            db, _quotes, _notifier, _time,
            Options.Create(_options),
            Options.Create(new AppOptions { PublicBaseUrl = "https://stonks.example.com" }),
            NullLogger<PriceCheckJob>.Instance);

        var run = await job.RunAsync();

        // The job swallows its own errors into the run record, so without this a broken job
        // would show up as a confusing downstream assertion rather than the actual cause.
        if (run.Status == JobStatus.Failed && _quotes.ThrowOnCall is null && _notifier.ThrowOnSend is null)
        {
            Assert.Fail($"Unexpected job failure: {run.Error}");
        }

        return run;
    }

    /// <summary>ASTS with invalidation 42, support 52-55, reclaim 59, target 70.</summary>
    private async Task SeedAstsAsync(decimal? lastQuote = null, CandidateStatus status = CandidateStatus.Watch)
    {
        await using var db = fixture.CreateContext();
        db.Candidates.Add(new Candidate
        {
            Id = Guid.NewGuid(),
            Ticker = "ASTS",
            Company = "AST SpaceMobile",
            Status = status,
            Invalidation = 42m,
            SupportLow = 52m,
            SupportHigh = 55m,
            ReclaimTrigger1 = 59m,
            T1 = 70m,
            LastQuote = lastQuote,
            CreatedAt = MarketOpen,
            UpdatedAt = MarketOpen
        });
        await db.SaveChangesAsync();
    }

    private async Task<List<Alert>> AlertsAsync()
    {
        await using var db = fixture.CreateContext();
        return await db.Alerts.OrderBy(a => a.LevelKey).ToListAsync();
    }

    private async Task<Candidate> CandidateAsync()
    {
        await using var db = fixture.CreateContext();
        return await db.Candidates.FirstAsync();
    }

    // ---------- First tick ----------

    [Fact]
    public async Task The_first_tick_records_the_quote_and_sends_nothing()
    {
        // Deploying the worker must not fire every already-breached level at once.
        await SeedAstsAsync(lastQuote: null);
        _quotes.Set("ASTS", 41m); // below invalidation

        var run = await RunAsync();

        Assert.Empty(_notifier.Sent);
        Assert.Empty(await AlertsAsync());
        Assert.Equal(41m, (await CandidateAsync()).LastQuote);
        Assert.Equal(JobStatus.Succeeded, run.Status);
        Assert.Equal(1, run.CandidatesChecked);
        Assert.Equal(0, run.AlertsFired);
    }

    // ---------- Crossing ----------

    [Fact]
    public async Task A_crossing_creates_an_alert_and_emails_once()
    {
        await SeedAstsAsync(lastQuote: 43m);
        _quotes.Set("ASTS", 41m);

        var run = await RunAsync();

        var alert = Assert.Single(await AlertsAsync());
        Assert.Equal(LevelKeys.Invalidation, alert.LevelKey);
        Assert.Equal(AlertType.Invalidation, alert.AlertType);
        Assert.True(alert.Triggered);
        Assert.True(alert.AutoGenerated);
        Assert.Equal(MarketOpen, alert.TriggeredAt);
        Assert.Equal(41m, alert.TriggerPrice);
        Assert.Equal(MarketOpen, alert.LastNotifiedAt);

        var message = Assert.Single(_notifier.Sent);
        Assert.Contains("ASTS", message.Subject);
        Assert.Contains("broke invalidation", message.Subject);
        Assert.Equal(1, run.AlertsFired);
        Assert.Equal(1, run.NotificationsSent);
    }

    [Fact]
    public async Task Several_crossings_in_one_tick_arrive_as_a_single_digest()
    {
        await SeedAstsAsync(lastQuote: 57m);
        _quotes.Set("ASTS", 41m); // through support 55 and invalidation 42

        await RunAsync();

        var message = Assert.Single(_notifier.Sent);
        Assert.Contains("2 alerts", message.Subject);
        Assert.Contains("broke invalidation", message.PlainTextBody);
        Assert.Contains("entered primary support", message.PlainTextBody);
        Assert.Equal(2, (await AlertsAsync()).Count);
    }

    [Fact]
    public async Task Crossings_on_different_tickers_share_one_digest()
    {
        await SeedAstsAsync(lastQuote: 43m);
        await using (var db = fixture.CreateContext())
        {
            db.Candidates.Add(new Candidate
            {
                Id = Guid.NewGuid(), Ticker = "HIVE", ReclaimTrigger1 = 5m, LastQuote = 4m,
                Status = CandidateStatus.Watch, CreatedAt = MarketOpen, UpdatedAt = MarketOpen
            });
            await db.SaveChangesAsync();
        }

        _quotes.Set("ASTS", 41m).Set("HIVE", 6m);

        await RunAsync();

        var message = Assert.Single(_notifier.Sent);
        Assert.Contains("ASTS", message.Subject);
        Assert.Contains("HIVE", message.Subject);
    }

    // ---------- Suppression: the behaviour that matters most ----------

    [Fact]
    public async Task A_second_tick_at_the_same_price_sends_nothing()
    {
        await SeedAstsAsync(lastQuote: 43m);
        _quotes.Set("ASTS", 41m);

        await RunAsync();
        Assert.Single(_notifier.Sent);

        _time.Advance(TimeSpan.FromMinutes(15));
        var second = await RunAsync();

        // Still triggered, but inside the cooldown — no second email.
        Assert.Single(_notifier.Sent);
        Assert.Equal(0, second.AlertsFired);
    }

    [Fact]
    public async Task Drifting_further_past_a_level_does_not_re_notify()
    {
        await SeedAstsAsync(lastQuote: 43m);
        _quotes.Set("ASTS", 41m);
        await RunAsync();

        foreach (var price in new[] { 40m, 39m, 38m })
        {
            _time.Advance(TimeSpan.FromMinutes(15));
            _quotes.Set("ASTS", price);
            await RunAsync();
        }

        Assert.Single(_notifier.Sent);
    }

    [Fact]
    public async Task Oscillating_inside_the_re_arm_margin_does_not_re_notify()
    {
        // The spam scenario: a ticker chopping either side of its trigger.
        await SeedAstsAsync(lastQuote: 58m);
        _quotes.Set("ASTS", 59.5m);
        await RunAsync();
        Assert.Single(_notifier.Sent);

        foreach (var price in new[] { 58.9m, 59.2m, 58.85m, 59.4m })
        {
            _time.Advance(TimeSpan.FromMinutes(15));
            _quotes.Set("ASTS", price);
            await RunAsync();
        }

        Assert.Single(_notifier.Sent);
    }

    [Fact]
    public async Task A_persisting_condition_reminds_once_the_cooldown_expires()
    {
        await SeedAstsAsync(lastQuote: 43m);
        _quotes.Set("ASTS", 41m);
        await RunAsync();

        _time.Advance(TimeSpan.FromHours(7));
        await RunAsync();

        Assert.Equal(2, _notifier.Sent.Count);
    }

    [Fact]
    public async Task Acknowledging_an_alert_stops_the_reminders()
    {
        await SeedAstsAsync(lastQuote: 43m);
        _quotes.Set("ASTS", 41m);
        await RunAsync();

        await using (var db = fixture.CreateContext())
        {
            var alert = await db.Alerts.FirstAsync();
            alert.AcknowledgedAt = _time.GetUtcNow();
            await db.SaveChangesAsync();
        }

        _time.Advance(TimeSpan.FromHours(7));
        await RunAsync();

        Assert.Single(_notifier.Sent);
    }

    // ---------- Re-arming ----------

    [Fact]
    public async Task Clearing_a_level_re_arms_the_alert_so_it_can_fire_again()
    {
        await SeedAstsAsync(lastQuote: 58m);
        _quotes.Set("ASTS", 60m);
        await RunAsync();
        Assert.Single(_notifier.Sent);

        // Fall well clear of the 59 trigger — re-arms.
        _time.Advance(TimeSpan.FromMinutes(15));
        _quotes.Set("ASTS", 57m);
        await RunAsync();

        var rearmed = Assert.Single(await AlertsAsync());
        Assert.False(rearmed.Triggered);
        Assert.Null(rearmed.TriggeredAt);

        // Cross again after the cooldown — fires and emails a second time.
        _time.Advance(TimeSpan.FromHours(7));
        _quotes.Set("ASTS", 61m);
        await RunAsync();

        Assert.Equal(2, _notifier.Sent.Count);
        Assert.True((await AlertsAsync())[0].Triggered);
    }

    [Fact]
    public async Task A_re_armed_alert_reuses_its_row_rather_than_creating_another()
    {
        await SeedAstsAsync(lastQuote: 58m);
        _quotes.Set("ASTS", 60m);
        await RunAsync();

        _time.Advance(TimeSpan.FromMinutes(15));
        _quotes.Set("ASTS", 57m);
        await RunAsync();

        _time.Advance(TimeSpan.FromHours(7));
        _quotes.Set("ASTS", 61m);
        await RunAsync();

        Assert.Single(await AlertsAsync());
    }

    // ---------- Market hours ----------

    [Fact]
    public async Task A_tick_outside_market_hours_does_no_work()
    {
        _options.IgnoreMarketHours = false;
        await SeedAstsAsync(lastQuote: 43m);
        _quotes.Set("ASTS", 41m);
        _time.SetUtcNow(new DateTimeOffset(2026, 8, 1, 15, 0, 0, TimeSpan.Zero)); // Saturday

        var run = await RunAsync();

        Assert.Equal(JobStatus.Succeeded, run.Status);
        Assert.Contains("weekend", run.SkipReason);
        Assert.Equal(0, _quotes.CallCount);
        Assert.Empty(_notifier.Sent);
    }

    [Fact]
    public async Task Market_hours_can_be_ignored_for_local_testing()
    {
        _options.IgnoreMarketHours = true;

        await SeedAstsAsync(lastQuote: 43m);
        _quotes.Set("ASTS", 41m);
        _time.SetUtcNow(new DateTimeOffset(2026, 8, 1, 15, 0, 0, TimeSpan.Zero)); // Saturday

        await RunAsync();

        Assert.Single(_notifier.Sent);
    }

    // ---------- Candidate selection ----------

    [Fact]
    public async Task Invalidated_candidates_are_not_monitored()
    {
        await SeedAstsAsync(lastQuote: 43m, status: CandidateStatus.Invalidated);
        _quotes.Set("ASTS", 41m);

        var run = await RunAsync();

        Assert.Empty(_notifier.Sent);
        Assert.Equal("No candidates with levels to monitor", run.SkipReason);
    }

    [Fact]
    public async Task Entered_candidates_are_still_monitored()
    {
        // An open position breaking its invalidation is exactly the ping you want.
        await SeedAstsAsync(lastQuote: 43m, status: CandidateStatus.Entered);
        _quotes.Set("ASTS", 41m);

        await RunAsync();

        Assert.Single(_notifier.Sent);
    }

    [Fact]
    public async Task Candidates_with_no_levels_are_not_quoted()
    {
        await using (var db = fixture.CreateContext())
        {
            db.Candidates.Add(new Candidate
            {
                Id = Guid.NewGuid(), Ticker = "BARE", Status = CandidateStatus.Idea,
                CreatedAt = MarketOpen, UpdatedAt = MarketOpen
            });
            await db.SaveChangesAsync();
        }

        var run = await RunAsync();

        Assert.Equal(0, _quotes.CallCount);
        Assert.Equal("No candidates with levels to monitor", run.SkipReason);
    }

    [Fact]
    public async Task A_candidate_the_provider_could_not_price_is_skipped_quietly()
    {
        await SeedAstsAsync(lastQuote: 43m);
        _quotes.Clear(); // provider returns nothing for ASTS

        var run = await RunAsync();

        Assert.Equal(JobStatus.Succeeded, run.Status);
        Assert.Equal(0, run.CandidatesChecked);
        Assert.Empty(_notifier.Sent);
        Assert.Equal(43m, (await CandidateAsync()).LastQuote); // unchanged
    }

    // ---------- Failure handling ----------

    [Fact]
    public async Task A_provider_outage_is_recorded_as_a_failed_run()
    {
        await SeedAstsAsync(lastQuote: 43m);
        _quotes.ThrowOnCall = new HttpRequestException("upstream down");

        var run = await RunAsync();

        Assert.Equal(JobStatus.Failed, run.Status);
        Assert.Contains("upstream down", run.Error);
        Assert.Empty(_notifier.Sent);
        Assert.NotNull(run.FinishedAt);
    }

    [Fact]
    public async Task A_failed_email_keeps_the_alert_and_retries_next_tick()
    {
        await SeedAstsAsync(lastQuote: 43m);
        _quotes.Set("ASTS", 41m);
        _notifier.ThrowOnSend = new InvalidOperationException("smtp unreachable");

        var failed = await RunAsync();

        Assert.Equal(JobStatus.Failed, failed.Status);

        // Alert state survived the failed send, and was never marked as notified.
        var alert = Assert.Single(await AlertsAsync());
        Assert.True(alert.Triggered);
        Assert.Null(alert.LastNotifiedAt);

        // Next tick the email is retried even though the crossing itself cannot recur.
        _notifier.ThrowOnSend = null;
        _time.Advance(TimeSpan.FromMinutes(15));
        await RunAsync();

        Assert.Single(_notifier.Sent);
    }

    // ---------- Job bookkeeping ----------

    [Fact]
    public async Task Every_run_is_recorded()
    {
        await SeedAstsAsync(lastQuote: 43m);
        _quotes.Set("ASTS", 41m);

        await RunAsync();
        _time.Advance(TimeSpan.FromMinutes(15));
        await RunAsync();

        await using var db = fixture.CreateContext();
        var runs = await db.JobRuns.OrderBy(r => r.StartedAt).ToListAsync();

        Assert.Equal(2, runs.Count);
        Assert.All(runs, r => Assert.Equal(JobNames.PriceCheck, r.Job));
        Assert.All(runs, r => Assert.NotNull(r.FinishedAt));
        Assert.All(runs, r => Assert.Equal(JobStatus.Succeeded, r.Status));
    }

    [Fact]
    public async Task Hand_created_alerts_are_left_alone()
    {
        await SeedAstsAsync(lastQuote: 43m);
        await using (var db = fixture.CreateContext())
        {
            var candidate = await db.Candidates.FirstAsync();
            db.Alerts.Add(new Alert
            {
                Id = Guid.NewGuid(),
                CandidateId = candidate.Id,
                AlertType = AlertType.ReclaimTrigger,
                ConditionSignal = "daily close above with volume",
                LevelKey = null,
                Active = true
            });
            await db.SaveChangesAsync();
        }

        _quotes.Set("ASTS", 41m);
        await RunAsync();

        var alerts = await AlertsAsync();
        var manual = Assert.Single(alerts, a => a.LevelKey is null);
        Assert.False(manual.Triggered);
        Assert.False(manual.AutoGenerated);
        Assert.Equal("daily close above with volume", manual.ConditionSignal);
    }
}
