namespace StonkWatch.Web.Data.Entities;

public class Alert
{
    public Guid Id { get; set; }

    public Guid CandidateId { get; set; }
    public Candidate? Candidate { get; set; }

    public AlertType AlertType { get; set; }
    public decimal? LevelLow { get; set; }
    public decimal? LevelHigh { get; set; }
    public string? ConditionSignal { get; set; }

    /// <summary>
    /// Which candidate field produced this alert — see <see cref="LevelKeys"/>. Set on rows
    /// the price-check worker manages; null on alerts created by hand, which the worker
    /// leaves alone. Unique per candidate, so the worker can upsert on it.
    /// </summary>
    public string? LevelKey { get; set; }

    public bool Active { get; set; } = true;
    public bool Triggered { get; set; }
    public DateTimeOffset? LastChecked { get; set; }

    /// <summary>When the level was crossed. Null once the alert re-arms.</summary>
    public DateTimeOffset? TriggeredAt { get; set; }

    /// <summary>Price at the moment of crossing — what the notification quotes.</summary>
    public decimal? TriggerPrice { get; set; }

    /// <summary>Set from the UI to stop an alert being reported as needing attention.</summary>
    public DateTimeOffset? AcknowledgedAt { get; set; }

    /// <summary>Drives the per-alert notification cooldown.</summary>
    public DateTimeOffset? LastNotifiedAt { get; set; }

    public bool AutoGenerated { get; set; }
}

/// <summary>
/// The candidate price levels the worker monitors. These are persisted strings, so treat
/// them as a stable contract — renaming one orphans existing alert rows.
/// </summary>
public static class LevelKeys
{
    public const string SupportZone = "SupportZone";
    public const string SecondarySupportZone = "SecondarySupportZone";
    public const string ReclaimTrigger1 = "ReclaimTrigger1";
    public const string ReclaimTrigger2 = "ReclaimTrigger2";
    public const string Invalidation = "Invalidation";
    public const string T1 = "T1";
    public const string T2 = "T2";
}
