namespace StonkWatch.Web.Contracts;

public record AlertDto(
    Guid Id,
    Guid CandidateId,
    string Ticker,
    string AlertType,
    decimal? LevelLow,
    decimal? LevelHigh,
    string? ConditionSignal,
    bool Active,
    bool Triggered,
    DateTimeOffset? LastChecked,
    string? LevelKey = null,
    DateTimeOffset? TriggeredAt = null,
    decimal? TriggerPrice = null,
    DateTimeOffset? AcknowledgedAt = null,
    bool AutoGenerated = false);

public record CreateAlertRequest(
    string AlertType,
    decimal? LevelLow = null,
    decimal? LevelHigh = null,
    string? ConditionSignal = null,
    bool Active = true);

public record UpdateAlertRequest(
    bool? Active = null,
    bool? Triggered = null,
    string? ConditionSignal = null,
    decimal? LevelLow = null,
    decimal? LevelHigh = null);
